### ISSUE TITLE
ColumnMenu quirks

### ISSUE THREAD

**Issue by Grevinnan** [cronvel/terminal-kit#120] opened 2020-07-07 20:27 UTC
There are some quirks with the ColumnMenu that I found when having more items than fit in the screen.

1. If you don't specify pageMaxHeight then you don't get any "pages" at all, you can scroll through all elements but they only appear at the bottom of the menu.

2. I tried setting pageMaxHeight to some low number, then it worked quite nicely until the last page, it did not seem to clear the next-to-last pages content so that was rendered as well as the elements of the last page.

I use it in a layout so ideally I guess it should compute the pageMaxHeight from the layout in that case?

**Comment by cronvel** [comment] 2020-07-08 08:37
@Grevinnan Your 2) looks like a regression. For the Layout, like I said in the other issue, Layout are still experimental (yet backward compatible), and I specifically coded auto-resizing for TextBox inside Layout for issue #119 ... Now I have to do it for each relevant widgets.

**Comment by cronvel** [comment] 2020-07-08 09:35
@Grevinnan The bad redraw bug (your 2.) has been fixed as of v1.35.13.

I will look into the Layout thing later in the week, need some thinking about the API/behavior.

For your 1), by default, the column menu height is implicitly defined by its content (it can overflow, so if there is no Container to clip the overflow, there is no limit at all). Forcing a max height is done using `pageMaxHeight`. There is a bug/missing feature for menu-items using more than one line. That's what you are using?

**Comment by cronvel** [comment] 2020-07-09 17:22
@Grevinnan Can you test v1.36.0 and `./auto-resized-widgets-in-layout-test.js`, and tell me if it's what you expected?

`pageMaxHeight` is deprecated in favor of `maxHeight`, Layout should resize the ColumnMenu, and I hope all quirks are gone.

Thanks ;)

**Comment by Grevinnan** [comment] 2020-07-09 19:20
Yeah, It seems to be working fine! :smile: When I set autoWidth and autoHeight to true it behaved as I expected it to. When I did not set anything (width/height/autoX) I did not get any pages at all, only the elements that fit the first page, perhaps that is the intended behavior? I haven't thought about how the ColumnMenu should work in general.

**Comment by cronvel** [comment] 2020-07-09 20:24
Yes, *maxHeight* default to *Infinity*, i.e. no paging. So if there is too much items, it simply overflows. That's the intended behavior.

**Closed** 2020-07-11 19:06 UTC
